### PR TITLE
Resolve Python 2 __str__ method encoding errors

### PR DESCRIPTION
**Pull request by allanjamesvestal**
Requires a reversion to the old method of string formatting, unfortunately. @hobbes7878 This should work better in Python 3 than the first fix I attempted, but would you be able to verify that on a production Python 3 install?

### CODE REVIEW

**Comment by hobbes7878** [comment]
@allanjamesvestal Can we do the same thing using the unicode operator like this?

```python
u"{} - {} by {}".format(self.slug, self.title, self.author)		
```

**Comment by hobbes7878** [comment]
Also, would love to see a breaking example of what this is meant to fix in an issue.

**Comment by allanjamesvestal** [comment]
@hobbes7878 That appears to work! Revising the PR now.

One question, though: do we have to worry about that causing any knock-on effects in Python 3 (where something might be expecting an `str` rather than a `unicode` type)?

**Comment by allanjamesvestal** [comment]
So, the breaking instance was one in which a `chartwerk.models.Chart` was created with a title that included a curly quote. (In this case, with a right single quote.)

Then, when attempting to load that chart in the admin change view, I get a 500 from a `UnicodeEncodeError` stating that `'ascii' codec can't encode character u'\u2019'`.

This probably throws similar errors in other places where the `__str__()` method is called, but this was the use case that tipped me off to it.

**Comment by hobbes7878** [comment]
Can you put that example in an issue that we can close with this PR? Was this a Python 2 version it's failing in?

Reading [this](https://docs.djangoproject.com/en/1.11/topics/python3/#str-and-unicode-methods), I think the answer _may be_ to use the built-in decorator.

**Comment by allanjamesvestal** [comment]
Filed #72. I'm not set up to test that decorator in my local env, but if someone else wants to give it a try and report back I'd be happy to add that instead of the unicode type-coercion I'm doing now.

**Comment by hobbes7878** [comment]
I can give it a whirl, but I see it in lots of other places now, too. Pretty sure it's what we're missing.

**Comment by hobbes7878** [comment]
Hey @allanjamesvestal, just looking at this but in Python 3 that decorator is a noop. It's actually in 2 that it does something. If that's your setup, then I'd say you're better to test it than I am.

But generally, I'm positive now we need to add that decorator for compatibility. If you want to amend the PR for that, I'd say let's merge it.

**Comment by allanjamesvestal** [comment]
OK, looks like the decorator works when combined with the `u'<format_string'` you'd suggested previously. Pushed up a commit with both.

**Comment by allanjamesvestal** [comment]
@hobbes7878 Can you take a look at this when you get a chance in the next several days? We're getting close to being able to ship this as a new version with the fix.

**Comment by hobbes7878** [comment]
Hey @allanjamesvestal does your branch need some cleaning up here? Looks like there are _a lot_ of file changes unrelated to the string formatting fix. Worried about regressing chartwerk-editor (the static files) and maybe some other stuff we've written in the interim...

**Comment by allanjamesvestal** [comment]
@hobbes7878  I'd be happy to spike this PR, since we're on Python 3 now as well.

We can leave this open if there's any particular need out there for Python 2 support, but I'd imagine that's less of a concern now than it was 6 or 12 months ago. (Hopefully.)

**Comment by achavez** [comment]
@allanjamesvestal suggested we spike this, since we are no longer as concerned with Python 2 support, so I'm closing this and the associated issue.

**Pull request closed without merging**
