### PR TITLE
Bugfix/config error call type enhancements

### PR DESCRIPTION
**Pull request by allanjamesvestal**
@hobbes7878 This would modify when config errors get kicked off to avoid matching on all falsy values (including empty strings).

### CODE REVIEW

**Comment by hobbes7878** [comment]
Wait, don't we want to throw errors on empty strings for required config?

(P.S. your code from #70 is in here, too.)

**Comment by hobbes7878** [comment]
OK, I see your issue. I'll buy that if it keeps us in step with Boto. Will approve.

**Comment by allanjamesvestal** [comment]
I wouldn't think so — both `Boto` and `django-storages` treat those as valid inputs, and leave any error messaging around empty strings to the actual places where they're called. This makes local dev easier, since we don't require these credentials to be set to a (plausibly) accurate value just to get started.

Thanks for the heads-up on the code inclusion. Running out now but can work up a version without that after I'm back in front of a computer.

**Comment by allanjamesvestal** [comment]
OK, this should be a clean version.

**Comment by allanjamesvestal** [comment]
Revisiting this today. I'll merge this in in the next day, unless there's some reason I shouldn't at this point.

**Comment by achavez** [comment]
Merging this, as it looks like all concerns from previous reviews were addressed

**Pull request merged**
