### PR TITLE
JS compiler subprocess. Example app.

### PR DESCRIPTION
**Pull request by hobbes7878**
The big add: this adds a subprocess step before publishing so you can compile JavaScript by piping through a node-based CLI compiler.

If y'all are on Heroku, like we are, and want to use this to write charts in ES2015+, you need to add a second buildpack for node. You can do that in the online dashboard now (sooooo much easier than it used to be), but **importantly** your python buildpack needs to be the **last one** in the list. Then just drop a `package.json` in the root of the repo with the compiler dependencies and should be good.

This also adds an example app in the repo so we can more easily test new features as we go.

### CODE REVIEW

**Comment by achavez** [comment]
I really like this addition. Unfortunately, `subprocess.run` is Python 3-only. It looks like there are Python 2 alternatives, but it's not clear to me if we'd be giving up some of the functionality of `subprocess.run` so I'm not sure what the best solution is here. Maybe importing from `future` is enough? http://python-future.org/compatible_idioms.html#commands-subprocess-modules

I guess all that begs the question, if making this work on both is non-trivial: How much longer do we care about Python 2 support?

**Comment by hobbes7878** [comment]
I mean, I'd be ready to move on in step with Django 2. We're on Python 3 with it, already.

That said, I think I could refactor with [subprocess.check_call](https://docs.python.org/2/library/subprocess.html#subprocess.check_call) if you all want to hold on to 2 a little longer.

Up to you.

**Comment by achavez** [comment]
It it'll work all the same with `check_call` - and it's not too much of a hassle - that'd be great. We'd like to get to Python 3 soon, but I suspect we won't be all the way there until early next year.

**Comment by hobbes7878** [comment]
Okey dokey. That should do it.

Marking this for `0.5.17`, though it looks like we've still got some open PRs from @allanjamesvestal we could lump into a release.

**Comment by achavez** [comment]
OK, took a crack at running this on Python 2. Unfortunately, while `check_output` works, the `input=` parameter does not exist and the closest alternative I could find that _appears_ to be compatible across versions is to use `Popen` with `.communicate()`. I pushed up a branch that works for us on Python 2: https://github.com/DallasMorningNews/django-chartwerk/compare/subprocess...subprocess-py2

**Comment by hobbes7878** [comment]
I suppose this is why you test Py2 code in a Py2 env...

I dig it! Let's put it in.

**Comment by achavez** [comment]
@hobbes7878 Done. Merged into this branch.

I'm about to be out for a few days, so we'll probably put this into prod next week and I'll do some more testing then.

**Comment by hobbes7878** [comment]
Sweet. I'll let you know how it goes in 3.

**Pull request merged**
